# Generated by Django 3.2.7 on 2021-09-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientcredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(default='', max_length=30)),
                ('patient_last_name', models.CharField(default='', max_length=30)),
                ('patient_email', models.EmailField(default='', max_length=100)),
                ('patient_phonenumber', models.CharField(max_length=20)),
                ('patient_accountcreationtime', models.DateTimeField()),
                ('patient_username', models.CharField(max_length=20)),
            ],
        ),
    ]
