# Generated by Django 3.2.7 on 2021-09-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcredentials',
            name='patient_phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
