# Generated by Django 3.2.7 on 2021-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0002_alter_patientcredentials_patient_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcredentials',
            name='id',
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='patientcredentials',
            table='patients',
        ),
    ]
