# Generated by Django 3.2.7 on 2021-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0003_auto_20210930_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcredentials',
            name='patient_first_name',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
