# Generated by Django 3.2.7 on 2021-09-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0004_alter_patientcredentials_patient_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcredentials',
            name='patient_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientcredentials',
            name='patient_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
