# Generated by Django 3.2.7 on 2021-09-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0006_alter_patientcredentials_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientcredentials',
            old_name='patient_id',
            new_name='id',
        ),
    ]
