# Generated by Django 3.2.7 on 2021-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0007_rename_patient_id_patientcredentials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcredentials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
