# Generated by Django 3.2.7 on 2021-09-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0008_alter_patientcredentials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcredentials',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
