# Generated by Django 3.2.7 on 2021-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0009_alter_patientcredentials_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='Male', max_length=2),
        ),
    ]
