# Generated by Django 3.2.7 on 2021-10-01 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudrestapi', '0010_patientcredentials_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_bloodgroup',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_city',
            field=models.CharField(default='Kolkata', max_length=15),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_country',
            field=models.CharField(default='India', max_length=15),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_emergencycontact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_height',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_maritalstatus',
            field=models.CharField(default='Married', max_length=10),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_pincode',
            field=models.CharField(default='700000', max_length=15),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_state',
            field=models.CharField(default='WestBengal', max_length=15),
        ),
        migrations.AddField(
            model_name='patientcredentials',
            name='patient_weight',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='patientcredentials',
            name='patient_accountcreationtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
